import { FormEvent,useEffect,useRef,useState } from 'react'
import { Heart,X } from 'lucide-react'
import type { Book,LibraryStatus } from '../types'

const statuses:[LibraryStatus,string][]=[['WANT_TO_READ','Want to read'],['CURRENTLY_READING','Reading'],['READ','Read'],['DNF','Did not finish']]

export function ReadingDialog({book,onClose,onSave,onRemove,pending,error}:{book:Book;onClose:()=>void;onSave:(values:{status:LibraryStatus;rating?:number;favourite:boolean;dnf_reason?:string;recommend:boolean})=>void;onRemove?:()=>void;pending:boolean;error?:string}){
  const [status,setStatus]=useState<LibraryStatus>(book.status||'WANT_TO_READ');const [rating,setRating]=useState(book.rating?.toString()||'');const [favourite,setFavourite]=useState(Boolean(book.favourite));const [reason,setReason]=useState(book.dnf_reason||'');const [recommend,setRecommend]=useState(true);const numericRating=rating?Number(rating):undefined;const dialog=useRef<HTMLFormElement>(null)
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.focus();return()=>previous?.focus()},[])
  const keyDown=(event:React.KeyboardEvent)=>{if(event.key==='Escape'&&!pending){event.preventDefault();onClose()}if(event.key==='Tab'&&dialog.current){const focusable=[...dialog.current.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),textarea:not(:disabled),input:not(:disabled),a[href]')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
  const submit=(event:FormEvent)=>{event.preventDefault();onSave({status,rating:numericRating,favourite,dnf_reason:status==='DNF'?reason:undefined,recommend:status==='READ'&&Boolean(numericRating&&numericRating>=3.5)&&recommend})}
  return <div className="dialog-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&!pending&&onClose()}><form ref={dialog} tabIndex={-1} className="reading-dialog" role="dialog" aria-modal="true" aria-labelledby="reading-title" aria-describedby={error?'reading-error':undefined} onKeyDown={keyDown} onSubmit={submit}><button type="button" className="dialog-close" onClick={onClose} disabled={pending} aria-label="Close"><X/></button><span className="eyebrow">Update your library</span><h2 id="reading-title">{book.title}</h2><p>{book.author}</p><fieldset disabled={pending}><legend>Reading status</legend><div className="status-options">{statuses.map(([value,label])=><button type="button" key={value} className={status===value?'active':''} onClick={()=>setStatus(value)}>{label}</button>)}</div></fieldset><label>Rating (optional)<select disabled={pending} value={rating} onChange={event=>setRating(event.target.value)}><option value="">Not rated</option>{Array.from({length:10},(_,index)=>(index+1)/2).map(value=><option key={value} value={value}>{value} stars</option>)}</select></label><button disabled={pending} type="button" className={`favourite-toggle ${favourite?'active':''}`} onClick={()=>setFavourite(value=>!value)}><Heart size={18} fill={favourite?'currentColor':'none'}/>{favourite?'Favourite':'Add to favourites'}</button>{status==='READ'&&numericRating&&numericRating>=3.5&&<label className="confirm-check"><input disabled={pending} type="checkbox" checked={recommend} onChange={event=>setRecommend(event.target.checked)}/> Show recommendations with similar catalog themes after saving.</label>}{status==='DNF'&&<label>Why didn’t you finish? <span>(optional)</span><textarea disabled={pending} maxLength={500} rows={4} value={reason} onChange={event=>setReason(event.target.value)} placeholder="A private note for your library…"/><small>{reason.length}/500</small></label>}{error&&<p className="error" id="reading-error" role="alert">{error}</p>}<button className="button primary" disabled={pending}>{pending?'Saving…':'Save to library'}</button>{onRemove&&<button disabled={pending} type="button" className="remove-book" onClick={onRemove}>Remove from Library</button>}</form></div>
}
