import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { BookCheck, CircleAlert, Dna } from 'lucide-react'
import { DnaVisual } from '../components/DnaVisual'
import { api } from '../lib/api'

export function DnaPage(){
  const [showBooks,setShowBooks]=useState(false);const session=useQuery({queryKey:['auth','me'],queryFn:api.me,retry:false});const dna=useQuery({queryKey:['dna'],queryFn:api.dna,enabled:Boolean(session.data)})
  if(session.isPending)return <section className="page"><div className="empty">Loading…</div></section>
  if(!session.data)return <section className="page"><div className="empty"><Dna/><h1>Sign in to reveal your BookDNA</h1><p>Your DNA is private and forms from the books you read, rate, favourite, and leave unfinished.</p><Link className="button primary" to="/login?next=/dna">Sign in</Link> <Link className="button" to="/register?next=/dna">Create account</Link></div></section>
  const profile=dna.data;const classifications=profile?.completed_classifications||[]
  return <section className="page dna-page"><div className="page-heading"><span className="eyebrow">The pattern behind your pages</span><h1>Your Book<span>DNA</span></h1><p>A transparent portrait based on the reading choices in your Library.</p></div><DnaVisual traits={profile?.traits||[]} profileConfidence={profile?.profile_confidence||0} confidenceLabel={profile?.confidence_label||'Early'}/><div className="completion-summary"><strong>{profile?.completed_books??0} of {profile?.total_books??0} books read — {profile?.completion_rate??0}%</strong><span>This is your completion rate. It is separate from profile confidence.</span></div><div className="dna-explain"><button onClick={()=>setShowBooks(value=>!value)} aria-expanded={showBooks}><strong>{profile?.books_shaping??0}</strong><span>books shaping your DNA</span><small>{showBooks?'Hide details':'See which books count'}</small></button><article><strong>{profile?.active_traits??0}</strong><span>supported traits</span></article><article><strong>{profile?.active_categories??0}</strong><span>reading categories</span></article></div>{showBooks&&<section className="classification-panel"><div><h2>How your completed books are classified</h2><p>Academic books contribute to knowledge, literature, language, and reading-context traits. They are kept distinct from recreational genres.</p></div>{classifications.length?<div className="classification-list">{classifications.map(book=><article key={book.id} className={book.included?'included':'needs-classification'}>{book.included?<BookCheck/>:<CircleAlert/>}<div><h3>{book.title}</h3><p>{book.author||'Unknown author'} · {book.reading_type==='academic'?'Academic reading':'Recreational reading'}</p><span>{book.included?'Included':'Needs classification'}</span><small>{book.reason}{book.traits.length?` Traits: ${book.traits.join(', ')}.`:''}</small></div></article>)}</div>:<p>No completed books yet.</p>}</section>}<p className="metric-explanation"><b>Profile confidence</b> grows from classified completed books, ratings, repeated support for traits, and breadth across categories. A single book is treated as an early clue, not an established preference.</p></section>
}
