export type SupportingBook={id:string;title:string;author?:string;rating?:number;favourite:boolean;evidence:number}
export type Trait = { id: string; name: string; category: string; score: number; confidence: number; supporting_books?:SupportingBook[] }
export type Book = { id: string; title: string; author: string; year?: number; cover_url?: string; subjects?: string[]; edition_count?: number; isbn?: string[]; source?: string; status?: LibraryStatus; rating?: number; favourite?: boolean; dnf_reason?: string }
export type BookSearch = { books: Book[]; page: number; limit: number; total: number; has_more: boolean; source: string }
export type BookCollection = { id: string; name: string; query: string }
export type LibraryStatus = 'READ' | 'CURRENTLY_READING' | 'WANT_TO_READ' | 'DNF'
export type User = { id: string; username: string }
export type Profile = User & { email:string;display_name?:string;timezone:string;date_format:string;language:string;avatar:string }
export type DnaProfile={traits:Trait[];evidence:number;profile_confidence:number;confidence_label:string;books_shaping:number;completed_books:number;active_traits:number;active_categories:number}
export type RecommendationBook=Book&{reason:string}
export type AdminStats = { totals: { registrations:number; logins:number; active_24h:number; active_30d:number; books_saved:number; dna_generated:number }; daily: { day:string; registrations:number; logins:number; books_saved:number; dna_generated:number }[] }
